language: go

services:
  - docker

cache:
  directories:
    - /home/travis/.docker/cli-plugins

before_install:
  - mkdir -p /home/travis/.docker/cli-plugins/
  - curl -SL https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
  - chmod +x ~/.docker/cli-plugins/docker-compose
  - docker compose version

script:
  - cd Chapter8
  - docker compose -f docker-compose.yaml -f newsletter-lambda/docker-compose.yaml -f s3store-lambda/docker-compose.yaml -f sqs-to-lambda/docker-compose.yaml build
